apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: default
spec:
  ports:
  - nodePort: 32200
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: caddy
  sessionAffinity: None
  type: NodePort
