apiVersion: v1
kind: Service
metadata:
  name: nginx-tls
  namespace: default
spec:
  ports:
  - nodePort: 32200
    port: 80
    name: http
    protocol: TCP
    targetPort: http
  - nodePort: 32443
    port: 443
    name: https
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-tls
  sessionAffinity: None
  type: NodePort
