apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: default
spec:
  ports:
  - nodePort: 32300
    port: 80
    name: http
    protocol: TCP
    targetPort: http
  - nodePort: 32400
    port: 443
    name: https
    protocol: TCP
    targetPort: https
  selector:
    app: caddy
  sessionAffinity: None
  type: NodePort
