apiVersion: v1
kind: ReplicationController
metadata:
  name: caddy-router
spec:
  replicas: 1
  selector:
    app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - image: quay.io/robszumski/k8s-ssl-termination
        name: caddy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
